### PR TITLE
Request Resource returns weak_ptr

### PR DESCRIPTION
**Pull request by gerard-queralt**
`ModuleResources::RequestResource` returns weak pointer instead of shared. Also made minimal changes to allow the project to compile.
Important to bear in mind that a `weak_ptr` can't be assigned to `nullptr`; instead, use the default constructor as shown in `ModuleResources::RequestResource`

### CODE REVIEW

**Comment by gerard-queralt** [comment]
@markmeliaa I made minor changes to the `ComponentMeshRenderer` so it has a `weak_ptr` instead of a shared one. Make sure I didn't break anything, and if I didn't, you can use it as reference for future components.

**Comment by markmeliaa** [comment]
As far as I can see, everything seems right, thank you Gerard for that change 👍

**Review by markmeliaa — APPROVED** [review]

**Comment by gerard-queralt** [comment]
I just realized that calling `weak_ptr::lock` without a check could thorw a NPE. I will add that check, so don't merge just yet, sorry!

**Comment by gerard-queralt** [comment]
After checking the documentation and doing some tests, it seems that calling `weak_ptr::lock` on an empty pointer throws no error; instead, it just returns another empty pointer. Calling that one does raise a NPE, but it would happen regardless if we are using shared or weak pointers, so no new errors should be added after merging this branch. All clear!

**Comment by markmeliaa** [comment]
Great, thanks for looking into it!

**Review by markmeliaa — APPROVED** [review]

**Review by AuxPort66 — APPROVED** [review]

**Pull request merged**
