### PR TITLE
Merge inspector-create-components into scenemanagement

### PR DESCRIPTION
**Pull request by sncarbo**

### CODE REVIEW

**Review by diegusmejia117 — DISMISSED** [review]
Well done Santi, hope you can rest a little at last.

**Comment by sncarbo** [comment]
Thank you Diego! We deserve a rest. @diegusmejia117

**Review by diegusmejia117 — APPROVED** [review]
well done!

**Review by totisama — APPROVED** [review]

**Comment by markmeliaa** [comment]
Do not merge this please, I have some changes to request.

**Comment by markmeliaa** [comment]
Nevermind

**Comment by sncarbo** [comment]
Thank you Diego! @diegusmejia117

**Pull request merged**
