### PR TITLE
feat: Add a new function to start importation in Importer base class

### PR DESCRIPTION
**Pull request by ericdacal**
Add new base function to start importion in Importer class

### CODE REVIEW

**Review by gerard-queralt — CHANGES_REQUESTED** [review]
I think `Start` should also have an output parameter `U* ourMaterial`, just like `Import`.

**Comment by ericdacal** [comment]
I add the output parameter and change the name for Resource to be more clear.

**Review by gerard-queralt — CHANGES_REQUESTED** [review]
`Application.cpp` seems to have some temporary code

**Comment by ericdacal** [comment]
Removed temporary code from Application

**Review by gerard-queralt — APPROVED** [review]
Thank you very much!

**Review by AuxPort66 — APPROVED** [review]

**Pull request merged**
