### PR TITLE
Merge GameObject-Hierarchy into SceneManagement

### PR DESCRIPTION
**Pull request by totisama**

### CODE REVIEW

**Comment by markmeliaa** [comment]
@diegusmejia117 for the commits, please refer to the discord channel #programming_rules or check the Wiki of this repository, each commit should have a word before the message of the commit, briefing the objective/task developed in the commit https://github.com/Pre-SuperAwesomeEngine/Engine/wiki/Programming-rules.

I will finish revising this pull request tomorrow morning, I have a couple small issues regarding functionality but now I do not have the proper time to address them, sorry.

**Review by markmeliaa — CHANGES_REQUESTED** [review]
The main problem that I had when I tried this in VS is that, when I tried to compile the project, the new files WindowHierarchy.cpp and WindowHierarchy.h do not appear as included in the project and thus the project could not compile, did you had the same problem? Those files appear as included in your project? (Including images as reference of the problem).

a
aaa

And a requirement about funcionality, now the GameObjects in the hierarchy are wrongly displayed, for example, it appears "GameObject 1" and when you click in "GameObject 1" a child called "blah blah" is shown under it, but when I try to right click, only when right-clicking "blah blah" lets me create/delete a GameObject, and I think that that's not the funcionality we are seeking, instead, the "blah blah" objects should not appear and "GameObject 1", "GameObject 2"... should behave as the actual GameObjects, giving the possiblity to create childs/delete themselves when right-clicked. I hope you understand what I am saying, if not, feel free to ask for more clarification.

That is all for my part, good use of overrides btw, well done!

**Review by sncarbo — DISMISSED** [review]

**Comment by markmeliaa** [comment]
I resolved a conflict that appeared in the .vcxproj, all the changes are correct, thanks! :)

**Review by markmeliaa — APPROVED** [review]

**Review by diegusmejia117 — APPROVED** [review]
Reviewed functionality and code, functions correctly, well done team.

**Pull request merged**
