### PR TITLE
Merge Importers with Filesystem

### PR DESCRIPTION
**Pull request by ericdacal**
- feat: Implementation of an abstract base class Importer

### CODE REVIEW

**Comment by gerard-queralt** [comment]
I have a few questions, if you could tell me why you did it the way you did:

- Why do ModuleFileSystem::Load and Save return an unsigned int that is always 0?
- What is the `uint64_t` returned by Importer::Save?
- Why do the methods in Importer use output parameters instead of return types?

And sorry to be picky, but a couple things:

- The parameter `file_path` in the methods of ModuleFileSystem should be in camelCase
- If you could, organize your classes with filters in Visual Studio's solution explorer following the way you organized it in the project structure (so a FileSystem filter with an Importers filter inside)

**Comment by gerard-queralt** [comment]
Also, I noticed you included a file named FileSystem.h that is empty

**Comment by ericdacal** [comment]
Corrections:
- I refactor the filePath variable to CamelCase.
- I remove the unnused FileSystem.h
Answers:
- Importer::Save have to return IUD identificator of the resource
- FileSystem is only a basic version now, we have to improve then before. 
- Return 0 if the function doesn't have error and 1 if there is a error. But we need to create a catch for the error.
- That is base in the sliders of the teacher.

**Review by gerard-queralt — APPROVED** [review]
Great, thank you very much for the answers and for your work!

**Review by AuxPort66 — APPROVED** [review]

**Pull request merged**
